name: "Build for Demo"

on:
  push:
    branches:
      - main
    paths:
      - src/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build + Release Version
        id: build_number
        run: |
          echo "$(date -u '+%Y.%m.%d.%H%M%S')" >> timestamp.txt
          echo "RELEASE_VERSION=$(cat timestamp.txt)" >> $GITHUB_ENV

      - name: cat timestamp
        run: cat timestamp.txt

      - name: Upload App Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: timestamp.txt
          path: timestamp.txt

      - uses: release-drafter/release-drafter@v5
        id: draft-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prerelease: true

      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          draft: true
          tag: ${{ steps.draft-release.outputs.tag_name }}
          artifacts: 'timestamp.txt'
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          omitPrereleaseDuringUpdate: true
          replacesArtifacts: true