name: "Build for Demo"

on:
  push:
    branches:
      - main
    paths:
      - src/**
  workflow_dispatch:



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build + Release Version
        id: build_number
        run: |
          echo "$(date -u '+%Y.%m.%d.%H%M%S')" >> timestamp.txt
          echo "RELEASE_VERSION=$(cat timestamp.txt)" >> $GITHUB_ENV
          cat timestamp.txt

      - name: Remove any current draft releases
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          EXISTING_RELEASE_TAG=$(hub release -f "%T (%S) %n" --include-drafts | grep " (draft)" | awk '{print $1}')
          if [[ $EXISTING_RELEASE_TAG = *[!\ ]* ]]; then
            hub release delete $EXISTING_RELEASE_TAG
            echo "RELEASE_VERSION=$EXISTING_RELEASE_TAG" >> $GITHUB_ENV
          fi

      - name: Draft Release
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ env.RELEASE_VERSION }} -d -p --generate-notes 'timestamp.txt'

      - name: Upload App Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: timestamp.txt
          path: timestamp.txt