name: "Auto-Deployer Demo"

on:
  workflow_run:
    workflows: [Build for Demo]
    types: [ completed ]

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug 
      tags:
        description: 'Test scenario tags'
        required: false 
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true 

jobs:
  # start:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: echo stuff
  #       run: |
  #         echo ${{ toJSON(github.event) }}

  demo:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: demo
    steps:
    - name: Download Release
      run: |
        DRAFT_RELEASE=$(hub release -f "%T (%S) %n" --include-drafts | grep " (draft)" | awk '{print $1}')
        [[ ! -z "${DRAFT_RELEASE// }" ]] && gh release download $DRAFT_RELEASE -p 'timestamp.txt'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: cat timestamp
      run: cat timestamp.txt