name: "Auto-Deployer Stage or Prod"

on:
  release:
    types: [ published, released ]

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug 
      tags:
        description: 'Test scenario tags'
        required: false 
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true 

jobs:
  # start:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: echo stuff
  #       run: |
  #         echo ${{ toJSON(github.event) }}

  stage:
    runs-on: ubuntu-latest
    if: ${{ github.event.release.prerelease == true }}
    environment: stage
    steps:
    - uses: robinraju/release-downloader@v1.3
      name: download release asset
      with: 
        repository: ${{ github.repository }}
        tag: ${{ github.event.release.tag_name }}
        fileName: "*"

    - name: cat timestamp
      run: cat timestamp.txt

  prod:
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'released' && github.event.release.prerelease == false }}
    environment: prod
    steps:
    - uses: robinraju/release-downloader@v1.3
      name: download release asset
      with: 
        repository: ${{ github.repository }}
        tag: ${{ github.event.release.tag_name }}
        fileName: "*"

    - name: cat timestamp
      run: cat timestamp.txt