name: "Promote DEMO to STAGE"
on:
  workflow_dispatch:

jobs:
  get-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Publish the Current Draft Release
        run: |
          RELEASE_TAG=$(hub release -f "%T (%S) %n" --include-drafts | grep " (draft)" | awk '{print $1}')
          echo "$RELEASE_TAG"
          [[ ! -z "${RELEASE_TAG// }" ]] && hub release edit $RELEASE_TAG --draft=false -m ""
          [[ -z "${RELEASE_TAG// }" ]] && echo "Release Not Found"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}

      # - uses: ncipollo/release-action@v1
      #   with:
      #     token: ${{ secrets.GH_RELEASE_TOKEN }}
      #     allowUpdates: true
      #     draft: false
      #     tag: ${{ steps.get-deployment-action.outputs.ref }}
      #     omitBodyDuringUpdate: true
      #     omitNameDuringUpdate: true
      #     omitPrereleaseDuringUpdate: true 
